# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-14 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='books',
            field=models.ManyToManyField(related_name='Authors', to='books.Books'),
        ),
    ]
