# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-19 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='shows',
            name='release',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='store',
            name='title',
            field=models.ManyToManyField(related_name='Shows', to='shows.Shows'),
        ),
    ]
